language: java
after_success:
  - mvn clean test jacoco:report coveralls:report
  
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "asbOhFYFtpBsXNjo63pTKx4uAMK3AL8D/qLQkcORiR8uFvtHzWRckSGTC4V7qUi9BSL09AAHV/GpjGCjWPFzjK/YzHcyXL0KXWZgxAAqL5WCxxVTOqzvqUerk6xP4agcgC6kZZKnfPRgzWXibEdafKKFWOvuqUIm6j/R4653rFk27Nq1jOteKOIpcyzakUg3E4l4gZ6ieeG4oQTcc7EzLrDcFWZjPtCkAROp8TbEWggPT9N5rWUfn+hqi5M6YUqlFgW4LAgqE7VIs11N/O9JOglHKQM1JkQYchKzhdwY5pZB75S5/vJ2sqAmAK2nZGfr0hrtcfFZWmPCxRSf5MkgD06KpJ9Cx21iUYZR54Irk8nZYNvMZtxPXWOVH2Mg+kix535DqXJ/KTeC44qfkgh4NYC1wfZya5VT7ngOdBsgFfk6eRfw0xj/sFwlLT69uXrfPz26ztjl0tNZGbHcRmCAFPbbe/OkwjTFitRw7scXbcFiZ9VFikvL9JsfHpPdd2F1kjbKo4mlQjx79RRDwYKNA56T+EBPYheeJK8vDWqO9bZDLQ7qH83sl7vhU10BvO+6aaljqsb4hoFv1CCQ6WisOS4Fc8KWo4RvGi1eZDdBNtyKtTwPAaRUdQ2Na6AJFBMhGRlcT0j7nybjvPSMq0YxDKVPV/9QMx9Tq49UYRBXTCc="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "hjohn/hs.ddif"
      description: "Build submitted via Travis CI"
    notification_email: hjohn@xs4all.nl
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: master